# Generated by Django 5.0.7 on 2024-09-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_screen_seat_show_booking_theatre_screen_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
    ]
