# Generated by Django 5.0.7 on 2024-09-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_city', to='models.city'),
        ),
    ]
