# Generated by Django 5.0.7 on 2024-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_show_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
