# Generated by Django 5.0.7 on 2024-12-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
